spring:
  application:
    name: user-server
  config:
    import: optional:file:.env[.properties]

  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: false

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${AUTH_DB_SCHEMA}&stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${AUTH_DB_SCHEMA}

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_ACCESSTOKEN_EXPIRATION_MS:1800000}
    refresh-token-expiration-ms: ${JWT_REFRESHTOKEN_EXPIRATION_MS:1209600000}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 310
      password: ${REDIS_PASSWORD}

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}

feign:
  client:
    cultivation:
      url: ${CULTIVATION_SERVER_URL}


minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
